namespace TDGPGasReader.Consts
{
    public static class ResponsesTdgConfigConst
    {
        public const string PointResponseHeader = "*********************************************(Mini TDGP)***************************************\r\n                                  Oceanus Logger Main Menu\r\n                                      FW Version 1.1.26\r\n                                       Pro Oceanus Inc.\r\n\r\nDate: 2021/01/01 Time: 12:06:11\r\n\r\nSystem status:\r\nDetector ORT = 12.32 hours, Supply voltage = 11.9 volts, Mode = continuous\r\n***********************************************************************************************\r\n";
        public const string OptionsResponse = "\r\n***************************************************************************************\r\n  1) START sampling mode                6) Print status banner\r\n  2) STOP sampling                      s) Single sample acquisition in command mode\r\n  3) Setup sampling\r\n\r\n  4) View logged data                   t) Set clock time\r\n  5) Erase logged data                  b) Set baud rate\r\n\r\n***************************************************************************************\r\n\r\n>>";
        public const string SensorOn = "1\r\n\r\nSensor on.\r\n\r\n\r\n***************************************************************************************\r\n  1) START sampling mode                6) Print status banner\r\n  2) STOP sampling                      s) Single sample acquisition in command mode\r\n  3) Setup sampling\r\n\r\n  4) View logged data                   t) Set clock time\r\n  5) Erase logged data                  b) Set baud rate\r\n\r\n***************************************************************************************\r\n\r\n>>";
        public const string SensorOff = "2\r\n\r\n\r\nStopping sampling\r\n\r\n***************************************************************************************\r\n  1) START sampling mode                6) Print status banner\r\n  2) STOP sampling                      s) Single sample acquisition in command mode\r\n  3) Setup sampling\r\n\r\n  4) View logged data                   t) Set clock time\r\n  5) Erase logged data                  b) Set baud rate\r\n\r\n***************************************************************************************\r\n\r\n>>";
    }
}
